#!/usr/bin/env bash
# aws-ec2-bootstrap.sh — Tier-1 first-deploy to AWS EC2 from a local
# checkout. End-to-end: provisions one EC2 instance, waits for SSH,
# rsyncs the bootstrap bundle, runs install-podmaker.sh on the host.
#
# Requires on the operator workstation:
#   - aws-cli v2 (configured via AWS_PROFILE or env credentials)
#   - rsync, ssh, ssh-keygen
#   - bash >= 4 (associative arrays)
#
# Single-command shape:
#
#   ./scripts/bootstrap/aws-ec2-bootstrap.sh \
#       --domain panel.acme.io \
#       --email  ops@acme.io \
#       --region eu-central-1
#
# Optional flags:
#   --apex acme.io                  zone for Route53 A record (default: derived from --domain)
#   --instance-type t4g.medium      EC2 SKU (default: t4g.medium, arm64, 2 vCPU / 4 GB)
#   --ssh-key-name podmaker-ops     existing AWS key pair; if missing the script
#                                   imports a generated one and writes the private
#                                   key to ~/.ssh/<name>.pem
#   --hosted-zone-id Z123ABC        skip Route53 if blank
#   --tag-project podmaker          Name= tag on the instance
#   --skip-dns                      skip Route53 even with --apex
#   --dry-run                       print intended aws-cli commands, do nothing
#
# What lands on the box: docker-compose.bootstrap.yml + Caddyfile +
# secrets/control-plane.env (generated by install-podmaker.sh) +
# postgres + redis + openbao-meta + control-plane. Everything on ONE
# EC2 instance — bootstrap stack only. Promote to Tier-2 (multi-host,
# HA) through `pdctl topology import-ops` after the panel is live.

set -euo pipefail

# --- defaults ----------------------------------------------------------------

DOMAIN=""
EMAIL=""
REGION="${AWS_REGION:-${AWS_DEFAULT_REGION:-eu-central-1}}"
APEX=""
# T1 ships every container on this single instance: control-plane,
# 13 Go services, postgres, redis, openbao×2, step-ca, temporal,
# nats×4, zot. Needs ≥ 4 vCPU + 16 GB RAM + 80 GB disk to fit
# comfortably.
INSTANCE_TYPE="t4g.xlarge"
DISK_GIB=80
TIER="t1-single-host-aws"
SSH_KEY_NAME="podmaker-ops"
HOSTED_ZONE_ID="${PODMAKER_HOSTED_ZONE_ID:-}"
TAG_PROJECT="podmaker"
SKIP_DNS=0
DRY_RUN=0
SOURCE_DIR="$(cd "$(dirname "$0")/../.." && pwd)"

# --- parse args --------------------------------------------------------------

usage() { sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//'; }

while [ $# -gt 0 ]; do
    case "$1" in
        --domain)          DOMAIN="$2"; shift 2 ;;
        --email)           EMAIL="$2"; shift 2 ;;
        --region)          REGION="$2"; shift 2 ;;
        --apex)            APEX="$2"; shift 2 ;;
        --instance-type)   INSTANCE_TYPE="$2"; shift 2 ;;
        --disk-gib)        DISK_GIB="$2"; shift 2 ;;
        --tier)            TIER="$2"; shift 2 ;;
        --ssh-key-name)    SSH_KEY_NAME="$2"; shift 2 ;;
        --hosted-zone-id)  HOSTED_ZONE_ID="$2"; shift 2 ;;
        --tag-project)     TAG_PROJECT="$2"; shift 2 ;;
        --skip-dns)        SKIP_DNS=1; shift ;;
        --dry-run)         DRY_RUN=1; shift ;;
        --source)          SOURCE_DIR="$2"; shift 2 ;;
        --help|-h)         usage; exit 0 ;;
        *) echo "unknown arg: $1" >&2; usage >&2; exit 1 ;;
    esac
done

[ -n "$DOMAIN" ] || { echo "--domain required" >&2; exit 1; }
[ -n "$EMAIL"  ] || { echo "--email required"  >&2; exit 1; }
[ -n "$APEX" ]   || APEX=$(printf '%s' "$DOMAIN" | sed 's/^panel\.//')

log()  { printf '\033[1;36m[aws-bootstrap]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[aws-bootstrap]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[aws-bootstrap] ERROR:\033[0m %s\n' "$*" >&2; exit 1; }
run()  { if [ "$DRY_RUN" = "1" ]; then echo "  + $*"; else "$@"; fi; }

# --- prereqs -----------------------------------------------------------------

command -v aws       >/dev/null || die "aws-cli v2 not found (https://aws.amazon.com/cli)"
command -v rsync     >/dev/null || die "rsync not found"
command -v ssh       >/dev/null || die "ssh not found"
command -v ssh-keygen>/dev/null || die "ssh-keygen not found"
command -v jq        >/dev/null || die "jq not found (brew install jq)"

aws --version >/dev/null
aws sts get-caller-identity >/dev/null 2>&1 \
    || die "aws sts get-caller-identity failed — fix AWS_PROFILE / AWS_ACCESS_KEY_ID env"

CALLER=$(aws sts get-caller-identity --query Arn --output text)
log "AWS caller : $CALLER"
log "Region     : $REGION"
log "Domain     : $DOMAIN"
log "Apex       : $APEX"
log "Instance   : $INSTANCE_TYPE"
log "Source     : $SOURCE_DIR"

[ -f "$SOURCE_DIR/scripts/bootstrap/install-podmaker.sh" ] \
    || die "source dir missing scripts/bootstrap/install-podmaker.sh — pass --source"

# --- SSH key pair ------------------------------------------------------------

PRIVATE_KEY="${HOME}/.ssh/${SSH_KEY_NAME}.pem"

if aws ec2 describe-key-pairs --region "$REGION" --key-names "$SSH_KEY_NAME" >/dev/null 2>&1; then
    log "ssh key pair '$SSH_KEY_NAME' already in AWS"
    [ -f "$PRIVATE_KEY" ] \
        || die "AWS has key '$SSH_KEY_NAME' but $PRIVATE_KEY is missing locally — supply --ssh-key-name pointing at a pair you have"
else
    if [ -f "$PRIVATE_KEY" ]; then
        log "importing existing $PRIVATE_KEY as '$SSH_KEY_NAME'"
        PUB=$(ssh-keygen -y -f "$PRIVATE_KEY")
        run aws ec2 import-key-pair --region "$REGION" \
            --key-name "$SSH_KEY_NAME" \
            --public-key-material "$(printf '%s' "$PUB" | base64)"
    else
        log "creating new key pair '$SSH_KEY_NAME' (private key → $PRIVATE_KEY)"
        umask 077
        run aws ec2 create-key-pair --region "$REGION" \
            --key-name "$SSH_KEY_NAME" \
            --query 'KeyMaterial' --output text > "$PRIVATE_KEY"
        chmod 0600 "$PRIVATE_KEY"
    fi
fi

# --- AMI: latest Ubuntu 22.04 LTS arm64 via SSM Parameter Store --------------

AMI_PARAM="/aws/service/canonical/ubuntu/server/22.04/stable/current/arm64/hvm/ebs-gp2/ami-id"
log "resolving Ubuntu 22.04 arm64 AMI ($AMI_PARAM)"
AMI_ID=$(aws ssm get-parameter --region "$REGION" --name "$AMI_PARAM" \
    --query 'Parameter.Value' --output text)
[ -n "$AMI_ID" ] && [ "$AMI_ID" != "None" ] || die "AMI resolve failed"
log "AMI        : $AMI_ID"

# --- security group ---------------------------------------------------------

SG_NAME="podmaker-bootstrap"
SG_ID=$(aws ec2 describe-security-groups --region "$REGION" \
    --filters Name=group-name,Values="$SG_NAME" \
    --query 'SecurityGroups[0].GroupId' --output text 2>/dev/null || echo "None")

if [ "$SG_ID" = "None" ] || [ -z "$SG_ID" ]; then
    log "creating security group '$SG_NAME'"
    SG_ID=$(aws ec2 create-security-group --region "$REGION" \
        --group-name "$SG_NAME" \
        --description "PodMaker bootstrap (22/80/443)" \
        --query 'GroupId' --output text)
    run aws ec2 authorize-security-group-ingress --region "$REGION" \
        --group-id "$SG_ID" --protocol tcp --port 22  --cidr 0.0.0.0/0
    run aws ec2 authorize-security-group-ingress --region "$REGION" \
        --group-id "$SG_ID" --protocol tcp --port 80  --cidr 0.0.0.0/0
    run aws ec2 authorize-security-group-ingress --region "$REGION" \
        --group-id "$SG_ID" --protocol tcp --port 443 --cidr 0.0.0.0/0
    run aws ec2 authorize-security-group-ingress --region "$REGION" \
        --group-id "$SG_ID" --protocol udp --port 443 --cidr 0.0.0.0/0
else
    log "reusing security group '$SG_NAME' ($SG_ID)"
fi

# --- user-data (cloud-init) -------------------------------------------------
# Minimal: just install docker + signal ready. The heavy install runs
# *after* the script rsync's the bundle, not via user-data, so the
# operator sees real-time log output instead of polling /var/log.

USER_DATA=$(cat <<'CLOUD_INIT'
#cloud-config
package_update: true
packages:
  - curl
  - ca-certificates
  - rsync
runcmd:
  # Docker Engine + compose plugin from Docker's official repo —
  # Ubuntu's docker.io package does not ship the compose plugin.
  - curl -fsSL https://get.docker.com | sh
  - systemctl enable --now docker
  - usermod -aG docker ubuntu
  # Allow ubuntu to invoke `sudo -E` / `sudo VAR=val cmd` without
  # password. Default cloud-init sudoers drops the SETENV tag, so
  # the bootstrap installer fails at first run.
  - "printf 'ubuntu ALL=(ALL) NOPASSWD: SETENV: ALL\\n' > /etc/sudoers.d/90-podmaker-setenv && chmod 0440 /etc/sudoers.d/90-podmaker-setenv"
  - install -d -m 0755 /opt/podmaker-src /opt/podmaker
  - touch /var/run/podmaker-ready
CLOUD_INIT
)

# --- run instance ------------------------------------------------------------

log "launching EC2 instance"
INSTANCE_ID=$(aws ec2 run-instances --region "$REGION" \
    --image-id "$AMI_ID" \
    --instance-type "$INSTANCE_TYPE" \
    --key-name "$SSH_KEY_NAME" \
    --security-group-ids "$SG_ID" \
    --block-device-mappings "DeviceName=/dev/sda1,Ebs={VolumeSize=$DISK_GIB,VolumeType=gp3,DeleteOnTermination=true}" \
    --user-data "$USER_DATA" \
    --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=$TAG_PROJECT-cp},{Key=Project,Value=$TAG_PROJECT},{Key=Role,Value=bootstrap}]" \
    --query 'Instances[0].InstanceId' --output text)
[ "$DRY_RUN" = "1" ] && { log "dry-run: stopping after run-instances"; exit 0; }
log "instance   : $INSTANCE_ID — waiting until 'running'"
aws ec2 wait instance-running --region "$REGION" --instance-ids "$INSTANCE_ID"

# Elastic IP — stable across reboots; cheap (~$0/mo while attached).
log "allocating + associating Elastic IP"
ALLOC_ID=$(aws ec2 allocate-address --region "$REGION" --domain vpc \
    --tag-specifications "ResourceType=elastic-ip,Tags=[{Key=Name,Value=$TAG_PROJECT-cp},{Key=Project,Value=$TAG_PROJECT}]" \
    --query 'AllocationId' --output text)
aws ec2 associate-address --region "$REGION" \
    --instance-id "$INSTANCE_ID" --allocation-id "$ALLOC_ID" >/dev/null
PUBLIC_IP=$(aws ec2 describe-addresses --region "$REGION" \
    --allocation-ids "$ALLOC_ID" --query 'Addresses[0].PublicIp' --output text)
log "public IP  : $PUBLIC_IP"

# --- DNS (Route53) -----------------------------------------------------------

if [ "$SKIP_DNS" = "0" ]; then
    if [ -z "$HOSTED_ZONE_ID" ]; then
        HOSTED_ZONE_ID=$(aws route53 list-hosted-zones-by-name --dns-name "$APEX" \
            --query 'HostedZones[0].Id' --output text 2>/dev/null | sed 's|/hostedzone/||')
    fi
    if [ -n "$HOSTED_ZONE_ID" ] && [ "$HOSTED_ZONE_ID" != "None" ]; then
        log "upserting Route53 A record $DOMAIN -> $PUBLIC_IP (zone $HOSTED_ZONE_ID)"
        CHANGE=$(cat <<JSON
{"Changes":[{"Action":"UPSERT","ResourceRecordSet":{
    "Name":"$DOMAIN.","Type":"A","TTL":300,
    "ResourceRecords":[{"Value":"$PUBLIC_IP"}]}}]}
JSON
)
        aws route53 change-resource-record-sets \
            --hosted-zone-id "$HOSTED_ZONE_ID" \
            --change-batch "$CHANGE" >/dev/null
    else
        warn "no Route53 zone for $APEX — point A record for $DOMAIN at $PUBLIC_IP manually"
    fi
else
    warn "--skip-dns: point A record for $DOMAIN at $PUBLIC_IP manually before continuing"
fi

# --- wait for SSH ------------------------------------------------------------

log "waiting for SSH on $PUBLIC_IP:22 (up to 5 min)"
for i in $(seq 1 60); do
    if ssh -i "$PRIVATE_KEY" -o ConnectTimeout=5 -o StrictHostKeyChecking=no \
           -o UserKnownHostsFile=/dev/null -o BatchMode=yes \
           ubuntu@"$PUBLIC_IP" 'test -f /var/run/podmaker-ready' 2>/dev/null; then
        log "SSH up + cloud-init done"
        break
    fi
    sleep 5
    [ "$i" = "60" ] && die "SSH never came up (timeout)"
done

SSH="ssh -i $PRIVATE_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@$PUBLIC_IP"
SCP_RSYNC="rsync -az -e 'ssh -i $PRIVATE_KEY -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'"

# --- rsync the bootstrap bundle ---------------------------------------------

log "rsync bootstrap bundle to /opt/podmaker-src/"
eval $SCP_RSYNC --delete --relative \
    "$SOURCE_DIR/./deploy/docker-compose.prod.yml" \
    "$SOURCE_DIR/./deploy/docker-compose.bootstrap.yml" \
    "$SOURCE_DIR/./deploy/caddy/" \
    "$SOURCE_DIR/./deploy/bootstrap-templates/" \
    "$SOURCE_DIR/./scripts/bootstrap/" \
    "$SOURCE_DIR/./infra/vault/openbao/" \
    "$SOURCE_DIR/./infra/dev/nats/" \
    "$SOURCE_DIR/./infra/dev/zot/" \
    "$SOURCE_DIR/./tiers/" \
    ubuntu@"$PUBLIC_IP":/tmp/podmaker-src/

# Bundle into /opt/podmaker-src so the install script can find it via
# PODMAKER_SOURCE_BASE=file:///opt/podmaker-src.
$SSH 'sudo rm -rf /opt/podmaker-src && sudo mv /tmp/podmaker-src /opt/podmaker-src'

# --- run installer -----------------------------------------------------------

log "running install-podmaker.sh on host (tier=$TIER, mode=prod)"
$SSH "sudo PODMAKER_SOURCE_BASE=file:///opt/podmaker-src \
    /opt/podmaker-src/scripts/bootstrap/install-podmaker.sh \
    --domain '$DOMAIN' --email '$EMAIL' \
    --tier '$TIER' --mode prod --noninteractive"

# --- summary -----------------------------------------------------------------

cat <<TXT

\033[1;32m✓ PodMaker bootstrap complete.\033[0m

  Tier         ${TIER}
  Instance     ${INSTANCE_ID} (${INSTANCE_TYPE}, ${REGION}, ${DISK_GIB} GB)
  Public IP    ${PUBLIC_IP}  (Elastic IP ${ALLOC_ID})
  Panel        https://${DOMAIN}
  SSH          ssh -i ${PRIVATE_KEY} ubuntu@${PUBLIC_IP}
  Magic link   look in your inbox at ${EMAIL}

Next steps:
  1. If DNS isn't propagating: dig +short ${DOMAIN}
  2. Tail logs: ${SSH} 'cd /opt/podmaker && docker compose logs -f --tail=100'
  3. Inspect tier: ${SSH} 'cat /var/podmaker/tier-current.yaml'
  4. Promote to T2 (managed state) when you outgrow this box:
       pdctl auth login --panel https://${DOMAIN}
       pdctl tier promote --to t2-managed-aws --dry-run
       pdctl tier promote --to t2-managed-aws

Tear down everything created by this run:
  aws ec2 terminate-instances --region ${REGION} --instance-ids ${INSTANCE_ID}
  aws ec2 release-address     --region ${REGION} --allocation-id ${ALLOC_ID}
  aws ec2 delete-security-group --region ${REGION} --group-id ${SG_ID}
TXT
